import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

class PrivacyPolicy extends StatelessWidget {
  const PrivacyPolicy({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Privacy Policy',
              style: TextStyle(
                fontSize: 24.0,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 8.0),
            const Text(
              'Last updated: December 18, 2024',
              style: TextStyle(
                fontSize: 16.0,
                fontStyle: FontStyle.italic,
              ),
            ),
            const SizedBox(height: 16.0),
            const Text(
              'This Privacy Policy outlines our policies and procedures on the collection, use, and disclosure of your information when you use our Service. It also explains your privacy rights and how the law protects you.\n\nWe use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.',
            ),
            const SizedBox(height: 16.0),
            _buildSectionTitle('Interpretation and Definitions'),
            _buildSectionContent(
              'The words with capitalized initial letters have specific meanings as defined in the following section. These definitions have the same meaning whether they appear in singular or plural form.',
            ),
            _buildSectionTitle('Definitions'),
            _buildListItem(
                'Account: A unique account created for you to access our Service or parts of our Service.'),
            _buildListItem(
                'Affiliate: Any entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.'),
            _buildListItem(
                'Company: Refers to Evalogical PVT LTD, located at Technopark Phase 3, Trivandrum.'),
            _buildListItem(
                'Cookies: Small files placed on your computer, mobile device, or other device by a website, which contain details of your browsing history on that website, among other uses.'),
            _buildListItem('Country: Refers to Kerala, India.'),
            _buildListItem(
                'Device: Any device that can access the Service, such as a computer, cellphone, or digital tablet.'),
            _buildListItem(
                'Personal Data: Any information that relates to an identified or identifiable individual.'),
            _buildListItem(
                'Service: Refers to the Website and Mobile Application.'),
            _buildListItem(
                'Service Provider: Any natural or legal person who processes data on behalf of the Company.'),
            _buildListItem(
                'Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.'),
            _buildListItem(
                'Website: Refers to ShareMeDaily, accessible from https://sharemedaily.com/.'),
            _buildListItem(
                'You: Refers to the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.'),
            SizedBox(height: 16.0),
            _buildSectionTitle('Collection and Use of Your Personal Data'),
            _buildSectionTitle('Types of Data Collected'),
            _buildSectionSubtitle('Personal Data'),
            _buildSectionContent(
              'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. This may include, but is not limited to: Email address, Name, Phone number, Address, State, Province, ZIP/Postal code, City, and Usage Data.',
            ),
            _buildSectionSubtitle('Usage Data'),
            _buildSectionContent(
              'Usage Data is collected automatically when using the Service. This data may include information such as your device’s Internet Protocol (IP) address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.',
            ),
            _buildSectionContent(
              'When you access the Service through a mobile device, we may collect information such as the type of mobile device you use, your unique device ID, the IP address of your mobile device, your mobile operating system, and other diagnostic data.',
            ),
            _buildSectionTitle('Tracking Technologies and Cookies'),
            _buildSectionContent(
              'We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:',
            ),
            _buildListItem(
                'Cookies or Browser Cookies: A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.'),
            _buildListItem(
                'Web Beacons: Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).'),
            _buildSectionContent(
                'Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.'),
            _buildSectionContent(
                'We use both Session and Persistent Cookies for the purposes set out below: '),
            _buildListItem(
                'Necessary / Essential Cookies \nType: Session Cookies \nAdministered by: Us \nPurpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.'),
            _buildListItem(
                'Cookies Policy / Notice Acceptance Cookies \nType: Persistent Cookies \nAdministered by: Us \nPurpose: These Cookies identify if users have accepted the use of cookies on the Website. '),
            _buildListItem(
                'Functionality Cookies \nType: Persistent Cookies \nAdministered by: Us \nPurpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website. '),
            _buildSectionContent(
                'For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy. '),
            _buildSectionSubtitle('Use of Your Personal Data'),
            _buildSectionContent(
              'The Company may use Personal Data for the following purposes: ',
            ),
            _buildListItem(
                'To provide and maintain our Service, including to monitor the usage of our Service.'),
            _buildListItem(
                'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user. '),
            _buildListItem(
                'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service. '),
            _buildListItem(
                'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile applications push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. '),
            _buildListItem(
                'To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information. '),
            _buildListItem(
                'To manage Your requests: To attend and manage Your requests to Us. '),
            _buildListItem(
                'For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred. '),
            _buildListItem(
                'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience. '),
            _buildSectionContent(
                'We may share Your personal information in the following situations: '),
            _buildListItem(
                'With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. '),
            _buildListItem(
                'For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company. '),
            _buildListItem(
                'With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.'),
            _buildListItem(
                'With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions. '),
            _buildListItem(
                'With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. '),
            _buildListItem(
                'With Your consent: We may disclose Your personal information for any other purpose with Your consent. '),
            _buildSectionSubtitle('Retention of Your Personal Data'),
            _buildSectionContent(
                'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.'),
            _buildSectionContent(
                'The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.'),
            _buildSectionTitle('Transfer of Your Personal Data '),
            _buildSectionContent(
                'Your information, including Personal Data, is processed at the Companys operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. '),
            _buildSectionContent(
                'Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.'),
            _buildSectionContent(
                'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.'),
            _buildSectionTitle('Delete Your Personal Data'),
            _buildSectionContent(
                'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.'),
            _buildSectionContent(
                'Our Service may give You the ability to delete certain information about You from within the Service.'),
            _buildSectionContent(
                'You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.'),
            _buildSectionTitle('Disclosure of Your Personal Data '),
            _buildSectionSubtitle('Business Transactions'),
            _buildSectionContent(
                'If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy. '),
            _buildSectionSubtitle('Law enforcement'),
            _buildSectionContent(
                'Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).'),
            _buildSectionSubtitle('Other legal requirements '),
            _buildSectionContent(
                'The Company may disclose Your Personal Data in the good faith belief that such action is necessary to: '),
            _buildListItem('Comply with a legal obligation '),
            _buildListItem(
                'Protect and defend the rights or property of the Company '),
            _buildListItem(
                'Prevent or investigate possible wrongdoing in connection with the Service '),
            _buildListItem(
                'Protect the personal safety of Users of the Service or the public '),
            _buildListItem('Protect against legal liability '),
            _buildSectionSubtitle('Security of Your Personal Data '),
            _buildSectionContent(
                'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.'),
            _buildSectionTitle('Childrens Privacy '),
            _buildSectionContent(
                'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. '),
            _buildSectionContent(
                'If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parents consent before We collect and use that information. '),
            _buildSectionTitle('Links to Other Websites '),
            _buildSectionContent(
                'Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third partys site. We strongly advise You to review the Privacy Policy of every site You visit. '),
            _buildSectionContent(
                'We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. '),
            _buildSectionTitle('Changes to this Privacy Policy '),
            _buildSectionContent(
                'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. '),
            _buildSectionContent(
                'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy. '),
            _buildSectionContent(
                'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page. '),
            _buildSectionTitle('Contact Us'),
            _buildSectionContent(
                'If you have any questions about this Privacy Policy, You can contact us: '),
            Row(
              children: [
                Expanded(
                  child: RichText(
                    textAlign: TextAlign.center,
                    text: TextSpan(
                      text: 'By visiting this page on our website:',
                      style: Theme.of(context).textTheme.bodyMedium,
                      children: const <InlineSpan>[
                        TextSpan(
                          text: 'By visiting this page on our website:'
                        ),
                        WidgetSpan(
                          alignment: PlaceholderAlignment.baseline,
                          baseline: TextBaseline.alphabetic,
                          child: LinkButton(
                              urlLabel: "evalogical.com",
                              url: "https://evalogical.com/"),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            )
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 20.0,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  Widget _buildSectionSubtitle(String subtitle) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0, bottom: 4.0),
      child: Text(
        subtitle,
        style: const TextStyle(
          fontSize: 18.0,
          fontWeight: FontWeight.w600,
        ),
      ),
    );
  }

  Widget _buildSectionContent(String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        content,
        style: const TextStyle(
          fontSize: 16.0,
        ),
      ),
    );
  }

  Widget _buildListItem(String content) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text('•'.toString(), style: const TextStyle(fontSize: 20.0)),
          const SizedBox(width: 8.0),
          Expanded(
            child: Text(
              content,
              style: const TextStyle(fontSize: 16.0),
            ),
          ),
        ],
      ),
    );
  }
}

class LinkButton extends StatelessWidget {
  const LinkButton({Key? key, required this.urlLabel, required this.url})
      : super(key: key);

  final String urlLabel;
  final String url;

  Future<void> _launchUrl(String url) async {
    final Uri uri = Uri.parse(url);

    if (!await launchUrl(uri)) {
      throw 'Could not launch $uri';
    }
  }

  @override
  Widget build(BuildContext context) {
    return TextButton(
      style: TextButton.styleFrom(
        padding: EdgeInsets.zero,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(0),
        ),
        tapTargetSize: MaterialTapTargetSize.shrinkWrap,
        visualDensity: VisualDensity.compact,
        minimumSize: const Size(0, 0),
        textStyle: Theme.of(context).textTheme.bodySmall,
      ),
      onPressed: () {
        _launchUrl(url);
      },
      child: Text(urlLabel),
    );
  }
}
